version: '3'
services:
  flyway:
    image: flyway/flyway:latest
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
      - ./postgres-docker.config:/flyway/conf/flyway.config
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=local-username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coverquest