name: CoverQuest Presubmit

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run fix
      - run: npm run test
      - run: npm run build
      - uses: EndBug/add-and-commit@v9
        with:
          add: "*"
