name: CoverQuest Presubmit

on:
  pull_request:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
      - name: Fix linting issues
        run: npm run fix
      - name: Lint
        run: npm run lint
      - name: Build with Next.js
        run: npm run build

      - name: Commit fixes
        uses: EndBug/add-and-commit@v9
        with:
          add: '*'
