name: CoverQuest Presubmit

on:
  pull_request:
    branches:
      - main

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
      - run: |
        touch .env
        echo GOOGLE_CLIENT_ID = ${{ secrets.GOOGLE_CLIENT_ID }} >> .env
        echo GOOGLE_CLIENT_SECRET = ${{ secrets.GOOGLE_CLIENT_SECRET }} >> .env
        echo NLB_API_KEY = ${{ secrets.NLB_API_KEY }} >> .env
        echo NLB_APP_CODE = ${{ secrets.NLB_APP_CODE }} >> .env
        echo DATABASE_URL = ${{ secrets.DATABASE_URL }} >> .env
        cat .env
      - run: npm install
      - run: npm run fix
      - run: npm run test
      - run: npm run build
      - uses: EndBug/add-and-commit@v9
        with:
          add: "*"
